
DETECT_QR="DETECT_QR"
DETECT_AR="DETECT_AR"
DETECT_PAPER="DETECT_PAPER"

SHADOW_ADNET = "SHADOW_ADNET"
SHADOW_HSI = "SHADOW_HSI"
SHADOW_DBRAR = "SHADOW_DBRAR"
SHADOW_YCBCR = "SHADOW_YCBCR"
SHADOW_LAB = "SHADOW_LAB"
#------------------------------
IS_DEBUG = True
DRAW_CONTOUROS=True
DETECT_TYPE=DETECT_AR
SHADOW_TYPE=SHADOW_ADNET

DRAW_HELP_WINDOWS=True

COLOR_TRANSFER=False
BRIGHTNESS_TRANSFER=True